
/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import com.google.gson.GsonBuilder;
import com.google.gson.reflect.TypeToken;
import org.junit.Test;

import static org.junit.Assert.*;

import java.lang.reflect.Type;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;

import com.google.gson.Gson;

public class AppTest {
    @Test
    public void testAppHasAGreeting() {
        App classUnderTest = new App();

        Gson gson = new GsonBuilder()
                .setPrettyPrinting()
                .create();
        // JsonOld: {"a":1,"b":1,"c":true,"array":[1,2,3],"object":{"arrayKey":["a","b","c","d"]}}
        String jsonOld = "{\"a\":1,\"b\":1,\"c\":true,\"array\":[1,2,3],\"object\":{\"arrayKey\":[\"a\",\"b\",\"c\",\"d\"]}}";
        // JsonNew: {"a":2,"b":1,"array":[1,2,3,2],"another":{"d":false,"e":["a","b","c"]},"object":{"booleanKey":true,"arrayKey":["a","b","c"]}}
        String jsonNew = "{\"a\":2,\"b\":1,\"array\":[1,2,3,2],\"another\":{\"d\":false,\"e\":[\"a\",\"b\",\"c\"]},\"object\":{\"booleanKey\":true,\"arrayKey\":[\"a\",\"b\",\"c\"]}}";

        Type mapType = new TypeToken<Map<String, Object>>() {
        }.getType();
        Map<String, Object> jsonOldAsMap = gson.fromJson(jsonOld, mapType);
        Map<String, Object> jsonNewAsMap = gson.fromJson(jsonNew, mapType);
        System.out.println("Old Json: " + gson.toJson(jsonOldAsMap));
        System.out.println("New Json: " + gson.toJson(jsonNewAsMap));
        System.out.println("========== Result ==========");
        // When
        boolean diff = classUnderTest.isDifference("", jsonOldAsMap, jsonNewAsMap);
        // Then
        assertTrue(diff);
    }
}
